name: Java CI

on: [push, pull_request]

jobs:
  buildJar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Set up PATH
        run: echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
      - name: General information
        run: |
          java --version
          d8 --version
      - name: Build and dexify mod jar file
        run: |
          chmod +x gradlew
          ./gradlew jar dex
      - name: Upload built mod jar file
        uses: actions/upload-artifact@v3
        with:
          name: Advance-Lighting (zipped)
          path: build/libs/Advance-Lighting.jar